apiVersion: traefik.io/v1alpha1 
kind: ServersTransport
metadata:
  name: proxmox-transport
  namespace: proxmox
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: proxmox
subsets:
  - addresses:
      - ip: 100.110.67.76
    ports:
      - name: https
        port: 8006
