longhornUI:
  replicas: 1
persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: "best-effort"
  reclaimPolicy: Retain
  migratable: true

metrics:
  serviceMonitor:
    enabled: true

defaultSettings:
  taintToleration: "postgres-db=true:NoSchedule"

longhornManager:
  tolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
longhornDriver:
  tolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
csi:
  attacherTolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  provisionerTolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  resizerTolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  snapshotterTolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
