apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: "Core Services"

  sourceRepos:
    - https://github.com/jcampos2907/homelab.git
    - https://charts.longhorn.io
    - https://stakater.github.io/stakater-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
