apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: "Monitoring and observability stack"

  sourceRepos:
    - https://github.com/jcampos2907/homelab.git
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
