apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula-sync
  template:
    metadata:
      labels:
        app: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.0
          env:
            - name: PIHOLE_PASS
              valueFrom:
                secretKeyRef:
                  name: pihole-admin
                  key: password
            # Primary should be pihole-0:
            - name: PRIMARY
              value: "http://pihole-0.pihole-headless.pihole.svc.cluster.local|$(PIHOLE_PASS)"
            - name: REPLICAS
              value: "http://pihole-1.pihole-headless.pihole.svc.cluster.local|$(PIHOLE_PASS)"
            - name: TZ
              value: America/Costa_Rica
            - name: FULL_SYNC
              value: "true"
            - name: RUN_GRAVITY
              value: "true"
            - name: CRON
              value: "*/2 * * * *"
          resources:
            requests:
              cpu: 20m
              memory: 32Mi