apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelabcluster
  namespace: homelab-pg
spec:
  managed:
    roles:
      - name: grafana
        superuser: true
        createrole: true
        login: true
  bootstrap:
    initdb:
      database: homelab
      owner: homelab
      secret:
        name: homelabcluster-user-homelab
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: homelab-init-scripts
            key: init-homelab.sql

  #   recovery:
  #     source: origin
  #     recoveryTarget:
  #       backupID: "20251124T000102"
  # externalClusters:
  #   - name: origin
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: minio-store
  #         serverName: homelabcluster
  # plugins:
  # - name: barman-cloud.cloudnative-pg.io
  #   isWALArchiver: true
  #   parameters:
  #     barmanObjectName: ceph-store
  monitoring:
    enablePodMonitor: true
  imageName: jicamposr/postgres:17.0
  imagePullPolicy: Always
  imagePullSecrets:
    - name: regcred
  postgresql:
    parameters:
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    shared_preload_libraries: 
    - "timescaledb"
 
  instances: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  storage:
    size: 50Gi
  affinity:
    podAntiAffinityType: required
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/pg_main
                operator: Exists
    # additionalPodAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         podAffinityTerm:
    #           labelSelector:
    #             matchExpressions:
    #               - key: app.kubernetes.io/name
    #                 operator: In
    #                 values:
    #                   - redis
    #           topologyKey: kubernetes.io/hostname
    tolerations:
    - key: "postgres-db"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

