apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana-db
spec:
  name: grafana-db
  owner: grafana
  schemas:
    - name: grafana
      owner: grafana
    - name: public
      owner: grafana
  cluster:
    name: homelabcluster