apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana
spec:
  name: grafana
  owner: grafana
  schemas:
    - name: grafana
      owner: grafana
    - name: public
      owner: grafana
  databaseReclaimPolicy: delete
  cluster:
    name: homelabcluster