apiVersion: v1
kind: ConfigMap
metadata:
  name: ccmbi-init-clientes
  namespace: ccmservices
data:
  init-clientes.sql: |
    CREATE OR REPLACE FUNCTION ccmbi.get_unmatched_clients(limit_count integer)
    RETURNS SETOF "ccmbi"."Clientes_Sirett"
    LANGUAGE plpgsql
    AS $function$
    DECLARE
        unmatched_record "ccmbi"."Clientes_Sirett";
        counter INT := 0;
    BEGIN
        FOR unmatched_record IN
            SELECT cs.*
            FROM "ccmbi"."Clientes_Sirett" cs
            LEFT JOIN clientes_location cl ON cs."ClienteID" = cl.sirett_id
            WHERE cl.sirett_id IS NULL and cs."IdTipo" =1
        LOOP
            EXIT WHEN counter >= limit_count;
            RETURN NEXT unmatched_record;
            counter := counter + 1;
        END LOOP;
        RETURN;
    END;
    $function$;


    CREATE TABLE "ccmbi"."clientes_location" (
    "sirett_id" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "nombre" text,
    "primer_apellido" text,
    "segundo_apellido" text,
    "dob" date,
    "cedula" text UNIQUE,
    "direccion" jsonb,
    CONSTRAINT "public_clientes_location_sirett_id_fkey" FOREIGN KEY ("sirett_id") REFERENCES "ccmbi"."Clientes_Sirett"("ClienteID") ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("sirett_id")
    );


    

    
    




