apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ceph-store
  namespace: homelab-pg
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://db-backups/
    endpointURL: http://pve-egress.default.svc.cluster.local:7480
    s3Credentials:
      accessKeyId:
        name: s3-creds
        key: ACCESS_KEY_ID_CEPH
      secretAccessKey:
        name: s3-creds
        key: ACCESS_SECRET_KEY_CEPH
    wal:
      compression: gzip
