---

apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: homelabcluster-pooler-ro
  namespace: homelab-pg
spec:
  serviceTemplate:
    metadata:
      annotations:
            tailscale.com/proxy-group: ingress-proxies
            tailscale.com/hostname: homelab-pgbouncer-ro 
    spec:
      type: LoadBalancer
      loadBalancerClass: "tailscale"
      ports:
      - name: pgbouncer
        port: 6432
        protocol: TCP
        targetPort: pgbouncer
  template:
    spec:
      containers: []
      # tolerations:
      # - key: "postgres-db"
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cnpg.io/podRole
                      operator: In
                      values:
                        - instance
                topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cnpg.io/poolerName
                operator: In
                values:
                - homelabcluster-pooler-ro
            topologyKey: "kubernetes.io/hostname"
  cluster:
    name: homelabcluster
  instances: 2
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"