---

apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: ccmcluster-pooler-rw
  namespace: ccmservices
spec:
  template:
    spec:
      containers: []
      tolerations:
      - key: "postgres-db"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/pg_main
                    operator: Exists
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cnpg.io/podRole
                      operator: In
                      values:
                        - instance
                topologyKey: kubernetes.io/hostname

        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cnpg.io/poolerName
                operator: In
                values:
                - ccmcluster-pooler-rw
            topologyKey: "kubernetes.io/hostname"
  cluster:
    name: ccmcluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  serviceTemplate:
    spec:
      type: LoadBalancer