apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ccmcluster-1
  namespace: ccmservices
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-a841e467-3131-41a5-bfa6-652aaa7a657e
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-debugger
  namespace: ccmservices
spec:
  containers:
    - name: shell
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: pgdata
          mountPath: /data
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: ccmcluster-1
  restartPolicy: Never
