apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip

resources:
  - sa.yaml
  - vault/vault-auth.yaml
  - vault/secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
