envFrom:
  - secretRef:
      name: oauth2-secrets

replicaCount: 2
proxyVarsAsSecrets: false
# ingress:
#   enabled: true
#   ingressClassName: traefik
#   hosts:
#     - oauth2.famcr.org
#   tls:
#     - secretName: oauth2-certificate-secret
#       hosts:
#         - oauth2.famcr.org

deploymentAnnotations: 
  reloader.stakater.com/auto: "true"

sessionStorage:
  type: redis
  redis:
    sentinel:
      existingSecret: oauth2-redis-secret
      passwordKey: 'sentinel-password'
      masterName: "homelabredis"
      connectionUrls:
        - "redis://oauth2-redis-announce-0.oauth2.svc.cluster.local:26379"
        - "redis://oauth2-redis-announce-1.oauth2.svc.cluster.local:26379"
    clientType: sentinel
   

redis:
  redis:
    masterGroupName: "homelabredis"
  existingSecret: oauth2-redis-secret
  enabled: true
  # architecture: standalone
  # usePassword: false
  sentinel:
    auth: true
    existingSecret: oauth2-redis-secret

  replicas: 2
  persistentVolume:
    enabled: true
    storageClass: "longhorn"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true