apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - sa.yaml
  - vault/sa.yaml
  - vault/vault-auth.yaml
  - vault/secrets.yaml
  - pvc.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
  - echo.yaml
