apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/type: master
  ports:
    - name: http
      port: 80
      targetPort: http
