---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: keycloak
  name: vault-auth
spec:
  vaultAuthGlobalRef:
    namespace: hashicorp
    allowDefault: true
  kubernetes:
    role: keycloak
