apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  namespace: hashicorp
  name: default
spec:
  allowedNamespaces:
    - oauth2
    - jenkins
    - cloudflare
    - argocd
    - homelab-pg
    - monitoring
    - tailscale
    - n8n
    - keycloak
    - onvo-mcp
  # vaultConnectionRef: vault-connection
  defaultAuthMethod: kubernetes
  kubernetes:
    audiences:
      - https://kubernetes.default.svc
    mount: kubernetes
    role: vault-apps
    serviceAccount: vault-sa
    tokenExpirationSeconds: 600
