apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-e0b6b72a-eeba-4e0f-bc91-cde822a10a40
  resources:
    requests:
      storage: 8Gi
