---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: jenkins
  name: vault-jenkins-secrets-static
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: apps/argocd
  refreshAfter: 60s
  destination:
    create: true
    name: argocd-secret-patch
    

    
