apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pihole.fullname" . }}-wait
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ include "pihole.fullname" . }}-waiter
      restartPolicy: Never
      containers:
        - name: waiter
          image: bitnami/kubectl:1.30
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              echo "Waiting for Pi-hole StatefulSet to become ready..."
              # Option A: wait on the StatefulSet rollout
              kubectl -n {{ .Release.Namespace }} rollout status statefulset/{{ include "pihole.fullname" . }} --timeout={{ default "10m" .Values.nebulaSync.waitTimeout }}
              # Option B (fallback): ensure all pods with the labels are Ready
              kubectl -n {{ .Release.Namespace }} wait pod -l app={{ template "pihole.name" . }},release={{ .Release.Name }} --for=condition=Ready --timeout={{ default "10m" .Values.nebulaSync.waitTimeout }}
              echo "Pi-hole is ready. Proceeding."
