apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pihole.fullname" . }}-waiter
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pihole.fullname" . }}-waiter
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pihole.fullname" . }}-waiter
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pihole.fullname" . }}-waiter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pihole.fullname" . }}-waiter
