apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-hl
  labels:
    app: {{ template "pihole.name" . }}
    app.kubernetes.io/name: {{ template "pihole.name" . }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true   # <— add this
  selector:
    app: {{ template "pihole.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: dns
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: http
      port: {{ .Values.webHttp }}
      protocol: TCP
