apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
  namespace: homelab-pg
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://db-backups/
    endpointURL: http://minio.minio-homelab.svc.cluster.local:80
    s3Credentials:
      accessKeyId:
        name: s3-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: s3-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
