---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: tailscale
  name: vault-tailscale-oauth
spec:
  vaultAuthRef: vault-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: operator
    - kind: Deployment
      name: nameserver
    - kind: StatefulSet
      name: egress-proxies
    - kind: StatefulSet
      name: ingress-proxies
    - kind: StatefulSet
      name: homelab-cluster
  mount: kv
  type: kv-v2
  path: apps/tailscale
  refreshAfter: 60s
  destination:
    create: true
    name: operator-oauth
    overwrite: true

  

    
