---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: tailscale
  name: vault-auth
spec:
  # kubernetes:
  #   role: vault-apps
  #   serviceAccount: vault-sa
  vaultAuthGlobalRef:
    namespace: hashicorp
    allowDefault: true
  kubernetes:
    audiences:
      - https://kubernetes.default.svc
    role: tailscale
