---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: jenkins
  name: vault-jenkins-secrets-static
spec:
  vaultAuthRef: vault-auth
  rolloutRestartTargets:
    - kind: StatefulSet
      name: jenkins
  mount: kv
  type: kv-v2
  path: apps/jenkinssources
  refreshAfter: 60s
  destination:
    create: true
    name: jenkins-oidc
    
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: jenkins
  name: vault-dockerhub-secrets-static
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: apps/dockerhub
  refreshAfter: 60s
  destination:
    create: true
    name: regcred

    
