apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: data-services

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  sources:
    - repoURL: https://github.com/jcampos2907/homelab.git
      targetRevision: main
      ref: values
      path: redis
      directory:
        recurse: true
        exclude: "{excluded/**}"
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 25.3.2
      helm:
        valueFiles:
          - $values/redis/values.yaml

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
