apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  namespace: hashicorp
  name: default
spec:
  allowedNamespaces:
    - jenkins
    - cloudflare
    - argocd
    
  # vaultConnectionRef: vault-connection
  defaultAuthMethod: kubernetes
  kubernetes:
    audiences:
    - vault
    mount: kubernetes
    role: vault-apps
    serviceAccount: vault-sa
    tokenExpirationSeconds: 600
