apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn