apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-restart-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coredns-restarter
  namespace: kube-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["coredns"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coredns-restart-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: coredns-restart-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: coredns-restarter
  apiGroup: rbac.authorization.k8s.io
