apiVersion: v1
home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
name: pihole-ha
description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional Unbound sidecar
version: 0.1.0
appVersion: "2025.08.0"
# Do not touch will be updated during release
sources:
  - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
  - https://pi-hole.net/
  - https://github.com/pi-hole
  - https://github.com/pi-hole/docker-pi-hole
icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
maintainers:
  - name: MoJo2600
    email: christian.erhardt@mojo2k.de
