---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  namespace: n8n
  name: n8n-dynamic
spec:
  vaultAuthRef: vault-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: n8n
  mount: database
  path: creds/n8n-dynamic
  destination:
    create: true
    name: n8n-user

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: n8n
  name: vault-n8n
spec:
  vaultAuthRef: vault-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: n8n
  mount: kv
  type: kv-v2
  path: apps/n8n
  refreshAfter: 60s
  destination:
    create: true
    name: n8n-encryption-key
    overwrite: true
