---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: n8n
  name: vault-n8n-redis
spec:
  vaultAuthRef: vault-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: n8n
    - kind: Deployment
      name: n8n-worker
  mount: kv
  type: kv-v2
  path: shared/redis
  refreshAfter: 60s
  destination:
    create: true
    name: n8n-redis-auth
