---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  namespace: n8n
  name: n8n-dynamic
spec:
  vaultAuthRef: vault-auth
  mount: database
  path: creds/n8n-dynamic
  destination:
    create: true
    name: n8n-user
